### ISSUE TITLE
Objective

### ISSUE THREAD

**Issue by tbergen1** [doctorpiorno/bwa-u4-feature-request#1]
I think this is a great feature addition to Jamming.  This is the first time I have seen this idea proposed by anyone and it is very useful.  I think you are right that the process of undoing actions is pretty difficult in the current iteration of Jamming, so being able to do that with the click of a button is awesome.  Good job thinking outside of the box here!

**Comment by doctorpiorno** [comment]
Thanks for the feedback! I wasn't sure my idea was going to be well-received as it wasn't the most challenging to implement, but I'm glad to see coming up with something original was appreciated. :)
