### ISSUE TITLE
Technical Implementation

### ISSUE THREAD

**Issue by tbergen1** [doctorpiorno/bwa-u4-feature-request#2]
Your technical implementation is extremely thorough.  You detailed everything that would need to be modified or added very well and demonstrated careful thought process in the design of this new feature.  Great job leveraging existing implementations of the code for your new feature as it is always good to re-use code in some way if possible to keep the code "DRY".  Overall, really great job here.

**Comment by doctorpiorno** [comment]
Thanks tbergen1! I did try to plan for all possible scenarios in advance but of course some unplanned difficulties came up during implementation. I'm glad I took the effort to actually do a test implementation of the feature!
