### ISSUE TITLE
Caveats

### ISSUE THREAD

**Issue by tbergen1** [doctorpiorno/bwa-u4-feature-request#3]
Your caveats section is great.  It shows that you put a lot of thought into this feature implementation.  The caveat sections of feature requests are usually very sparse, but your has a ton of information that shows that depth of thought.  You brought up some really good points regarding advantages of using certain arguments, especially from an extensibility standpoint for future features such as drag and drop.  Awesome work!

**Comment by doctorpiorno** [comment]
Thanks for the encouraging feedback. :)
