### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by tbergen1** [doctorpiorno/bwa-u4-feature-request#4]
Overall, this is one of the best feature requests I have seen.  Your feature request in and of itself was a unique one that showed that you wanted to add something really special to the application.  I admire that creativity, so great job there.  Your technical implementation details were extremely thorough and showed an incredible aptitude for feature design.  You clearly thought a lot about the process and even managed to reuse portions of the code to keep it "DRY".  Your caveats section then gave a nice list of advantages and drawbacks and showed you weighed your design options when making this documentation.  Lastly, I commend you for actually implementing this into your code.  Learners don't usually implement what they spec out in the feature request, so the fact that you did is awesome.  Really incredible job here!

**Comment by doctorpiorno** [comment]
Many thanks for your feedback. It encourages me to keep working on improving this app and maybe try implementing some of the suggested features!
